#!/usr/bin/env bash
# This script displays the time for 12 hours and 59 minutes

# Initialize variables for hours and minutes
hour=0
minute=1

# Use a while loop to display the time
while [ $hour -le 12 ]; do
  echo "Hour: $hour"
  
  while [ $minute -le 59 ]; do
    echo $minute
    ((minute++))
  done
  
  # Reset the minute counter and increment the hour
  minute=1
  ((hour++))
done
